name: CdPip
channels:
  - defaults
  - anaconda
  - conda-forge
  - spyder-ide
  - pytorch
  - districtdatalabs
dependencies:
  - anaconda
  - mpi4py
  - anaconda-clean
  - nb_conda
  - py-xgboost
  - pandas
  - pandas-datareader
  - pandas-profiling
  - graphviz
  - python-graphviz
  - plotly
  - holoviews
  - qgrid
  - pyqtgraph
  - pivottablejs
  - mlxtend
  - quandl
  - jupyterlab
  - joblib
  - dill
  - altair
  - jsonpickle
  - selenium
  - appmode
  - imageio
  - pydotplus
  - furl
  - streamz
  - catboost
  - lightgbm
  - pulp
  - fbprophet
  - tqdm
  - pyarrow
  - fastparquet
  - tabulate
  - gitpython
  - redis
  - keras
  - tensorflow
  - tensorboard
  - tensorflow-gpu
  - torchvision
  - tensorboardx
  - cudatoolkit
  - spyder-unittest
  - spyder-reports
  - tpot
  - python-cufflinks
  - pickleshare
  - scikit-optimize
  - prefect
  - simplejson
  - progressbar2
  - numba
  - tslearn
  - xarray
  - invoke
  - python-snappy
  - pyomo
  - paramiko
  - hickle
  - yellowbrick
  - shap
  - lime
  - watermark
  - appmode
  - grpcio
  - pytorch
  - spyder-notebook
  - pip
  - pip:
    - yfinance
    - multitasking
    - pyts
    - fastDTW
    - q
    - seasonal
    - pyclustering
    - knotter
    - dautil
    - jsonpath-ng
    - objectpath
    - flatten_json
    - pyjq
    - dpath
    - weasyprint
    - pdfkit
    - libjson2csv
    - ijson
    - dora
    - birdseye
    - vega_datasets
    - Pyppeteer
    - python-Levenshtein
    - datreant.data
    - flock
    - portalocker
    - datreant.core
    - datreant.data
    - libarchive-c
    - piecash
    - bqplot
    - py-cpuinfo
    - lolviz
    - textblob
    - pipdeptree
    - whoosh
    - pyautogui
    - meta
    - histbook
    - backtrader
    - edward
    - sacred
    - hone
    - watchdog
    - visdom
    - pip-tools
    - tableschema
    - tableschema-pandas
    - tableschema-sql
    - drawnow
    - hyperopt
    - hpsklearn
    - tensorforce
    - Prettytensor
    - code4th-datasource-air4thai
    - ticdat
    - bayesian-optimization
    - backtesting
    - seglearn
    - mpl-finance
    - pandas-bokeh
    - tsfresh
    - parfit
    - scikit-multiflow
    - resolvelib
    - steppy
    - stumpy
    - sktime
    - pysf
    - apscheduler
    - optuna
    - backtrader-plotting
    - sftpserver
    - pysftp

