name: CdPip
channels:
  - defaults
  - anaconda
  - conda-forge
  - spyder-ide
  - pytorch
  - districtdatalabs
dependencies:
  - anaconda
  - mpi4py
  - anaconda-clean
  - nb_conda
  - py-xgboost
  - pandas
  - pandas-datareader
  - pandas-profiling
  - graphviz
  - python-graphviz
  - plotly
  - holoviews
  - qgrid
  - pyqtgraph
  - pivottablejs
  - mlxtend
  - quandl
  - jupyterlab
  - joblib
  - dill
  - altair
  - jsonpickle
  - selenium
  - appmode
  - imageio
  - pydotplus
  - furl
  - streamz
  - catboost
  - lightgbm
  - pulp
  - fbprophet
  - tqdm
  - pyarrow
  - fastparquet
  - tabulate
  - gitpython
  - redis
  - keras
  - tensorflow
  - tensorboard
  - tensorflow-gpu
  - torchvision
  - tensorboardx
  - cudatoolkit
  - spyder-unittest
  - spyder-reports
  - tpot
  - python-cufflinks
  - pickleshare
  - scikit-optimize
  - prefect
  - simplejson
  - progressbar2
  - numba
  - tslearn
  - xarray
  - invoke
  - python-snappy
  - pyomo
  - paramiko
  - hickle
  - yellowbrick
  - shap
  - lime
  - watermark
  - appmode
  - grpcio
  - pytorch
  - spyder-notebook
  - pip


